In [6]:
import pandas as pd

In [7]:
file_path = "/content/datos_apartamentos_rent.xlsx"
df = pd.read_excel(file_path)

In [8]:
df = pd.DataFrame(df)
df

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,790,Monthly,101,NaN,Washington,DC,389057.0,-769861.0,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,425,Monthly,106,814 Schutte Rd,Evansville,IN,379680.0,-876621.0,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,1.39,Monthly,107,NaN,Arlington,VA,388910.0,-770816.0,RentLingo,1577359410
3,5659918074,housing/rent/apartment,Studio apartment 1717 12th Ave,"This unit is located at 1717 12th Ave, Seattle...",NaN,1.0,0.0,USD,No,Thumbnail,...,925,Monthly,116,1717 12th Avenue,Seattle,WA,476160.0,-1223275.0,RentLingo,1576667743
4,5668626759,housing/rent/apartment,"Studio apartment Washington Blvd, N Cleveland ...","This unit is located at Washington Blvd, N Cle...",NaN,NaN,0.0,USD,No,Thumbnail,...,880,Monthly,125,NaN,Arlington,VA,388738.0,-771055.0,RentLingo,1577359401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,5630240092,housing/rent/apartment,Five BR 5407 Abbott Place - Abbott,This unit is located at 5407 Abbott Place - Ab...,NaN,4.0,5.0,USD,No,Thumbnail,...,6,Monthly,6300,5407 Abbott Place Abbott,Edina,MN,449000.0,-933233.0,RentLingo,1575112975
9996,5668640983,housing/rent/apartment,Six BR 256 Las Entradas,"This unit is located at 256 Las Entradas, Mont...",NaN,8.0,6.0,USD,No,Thumbnail,...,25,Monthly,8716,256 Las Entradas,Montecito,CA,344331.0,-1196331.0,RentLingo,1577360419
9997,5668643292,housing/rent/apartment,Six BR 9908 Bentcross Drive,"This unit is located at 9908 Bentcross Drive, ...",NaN,8.5,6.0,USD,No,Thumbnail,...,11,Monthly,11318,9908 Bentcross Dr,Potomac,MD,390287.0,-772409.0,RentLingo,1577360560
9998,5668662559,housing/rent/apartment,One BR in New York NY 10069,"Monthly Rent$4,605 -to $4,790AmenitiesThe Aldy...","Basketball,Cable or Satellite,Doorman,Hot Tub,...",NaN,1.0,USD,No,Thumbnail,...,4.79,Monthly,40000,NaN,New York,NY,407716.0,-739876.0,Listanza,1577362186
9999,5509132540,housing/rent/apartment,Beautiful Lawrenceville Apartment for rent,"Square footage: 880 sq. feet, unit number: 150...","Gym,Patio/Deck",1.0,1.0,USD,No,No,...,1.009,Monthly,880,NaN,Lawrenceville,GA,340072.0,-840034.0,RentDigs.com,1577362141

In [9]:
# Extraer las comodidades de los inmueblde de la columna "amenities"
def get_unique_amenities(df, column="amenities"):
    unique_amenities = set()
    df[column].dropna().apply(lambda x: unique_amenities.update(x.split(",")))
    return list(unique_amenities)

In [10]:
# Obtener lista sin duplicados
unique_amenities_list = get_unique_amenities(df)
print(unique_amenities_list)

['Alarm', 'Doorman', 'Pool', 'Gated', 'Dishwasher', 'Playground', 'Internet Access', 'Hot Tub', 'Storage', 'Garbage Disposal', 'Gym', 'TV', 'Basketball', 'Cable or Satellite', 'Wood Floors', 'Golf', 'Elevator', 'Fireplace', 'Patio/Deck', 'Parking', 'Luxury', 'Clubhouse', 'AC', 'Washer Dryer', 'Tennis', 'View', 'Refrigerator']